# Generated by Django 3.1.7 on 2021-03-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='sname',
        ),
    ]
